name: Build RSDKv5
on:
  push:
    branches:
      - master

# TODO: readd with: submodules: recursive once we can

jobs:
  v5-windows:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: pkg-config make git mingw-w64-i636-gcc mingw-w64-i636-SDL2 mingw-w64-i636-libogg mingw-w64-i636-libvorbis mingw-w64-i636-libtheora
      - name: Clone theoraplay & tinyxml2
        run: |
          git clone https://github.com/icculus/theoraplay dependencies/all/theoraplay
          git clone https://github.com/leethomason/tinyxml2 dependencies/all/tinyxml2
      - name: Build RSDKv5
        run: |
          make -j8 
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./bin/Windows/*.dll ./artifacts 
          move ./bin/Windows/*.exe ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: v5-windows
          path: artifacts
  v5-windows-x64:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: pkg-config make git mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-libogg mingw-w64-x86_64-libvorbis mingw-w64-x86_64-libtheora
      - name: Clone theoraplay & tinyxml2
        run: |
          git clone https://github.com/icculus/theoraplay dependencies/all/theoraplay
          git clone https://github.com/leethomason/tinyxml2 dependencies/all/tinyxml2
      - name: Build RSDKv5
        run: |
          make -j8 
      - name: Move artifacts
        run: |
          mkdir artifacts
          move ./bin/Windows/*.dll ./artifacts 
          move ./bin/Windows/*.exe ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: v5-windows
          path: artifacts
  v5-android:
    runs-on: windows-latest
    steps:
      - name: Checkout repository Android
        uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Clone theoraplay & tinyxml2
        run: |
          git clone https://github.com/icculus/theoraplay dependencies/all/theoraplay
          git clone https://github.com/leethomason/tinyxml2 dependencies/all/tinyxml2
      - name: Download libogg, libvorbis, and libtheora
        run: |
          Invoke-WebRequest -Uri "https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.7.zip" -OutFile "libvorbis.zip"
          Expand-Archive -Path libvorbis.zip -DestinationPath ./dependencies/android/
          Rename-Item ./dependencies/android/libvorbis-1.3.7 libvorbis
          Invoke-WebRequest -Uri "https://ftp.osuosl.org/pub/xiph/releases/ogg/libogg-1.3.5.zip" -OutFile "libogg.zip"
          Expand-Archive -Path libogg.zip -DestinationPath ./dependencies/android/app/jni/src/dependencies/android/
          Rename-Item ./dependencies/android/app/jni/src/dependencies/android/libogg-1.3.5 libogg
          Invoke-WebRequest -Uri "https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.7.zip" -OutFile "libvorbis.zip"
          Expand-Archive -Path libvorbis.zip -DestinationPath ./dependencies/android/app/jni/src/dependencies/android/
          Rename-Item ./dependencies/android/app/jni/src/dependencies/android/libvorbis-1.3.7 libvorbis
      - name: Download SDL2
        run: |
          Invoke-WebRequest -Uri "https://libsdl.org/release/SDL2-2.0.16.zip" -OutFile "SDL2.zip"
          Expand-Archive -Path SDL2.zip -DestinationPath ./dependencies/android/
          Rename-Item ./dependencies/android/SDL2-2.0.16 SDL
      - name: Move & Copy stuff
        run: |
          Copy-Item -Path ./android/app/jni/src/dependencies/android\* -Destination ./dependencies/
          Copy-Item -Path ./android/app/jni/src/dependencies/android/libogg/ -Destination ./dependencies/android/ -recurse
          Copy-Item -Path ./android/config_types.h -Destination ./dependencies/android/libogg/include/ogg/
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11
      - name: Build RSDKv5
        working-directory: ./android
        run: |
          ./gradlew.bat Build --no-daemon -PABIFILTERS="armeabi-v7a;arm64-v8a"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: v5-android
          path: ./android/app/build/outputs/apk
  v5-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Clone theoraplay & tinyxml2
        run: |
          git clone https://github.com/icculus/theoraplay dependencies/all/theoraplay
          git clone https://github.com/leethomason/tinyxml2 dependencies/all/tinyxml2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libogg-dev libvorbis-dev libsdl2-dev libtheora-dev
          ls ./dependencies/all
      - name: Build RSDKv5
        run: make -j8
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: v5-linux
          path: bin
